### ISSUE TITLE
refactor: 0805 QA 진행

### ISSUE THREAD

**Issue by YesHyeon** [dnd-side-project/dnd-8th-5-frontend#118]
## ToDo

- [x] [첫페이지, 방생성 페이지] 배경 수정 

- [x] [일정등록 페이지] uuid 아무값 입력해도 오류 안뜨던 문제 해결 → 404 페이지 이동

- [x] [방생성 날짜선택 페이지] 캘린더 6줄일 때 날짜와 경계선 간격 ( qa-0805 브랜치 )
- [x] [방생성 날짜선택 페이지] 기간 한 번 선택하고, 다시 기간 선택할때 시작날짜만 선택해도 다음으로 넘어가지는 문제 

- [x] [404] 에러페이지 제작 및 잘못된 url 에러페이지로 라우팅

- [x] [공통] [modutime.site/ddsd](http://modutime.site/ddsd) 처럼 route에 없는 값 입력시 에러페이지 나오도록
- [x] [공통] 페이지 이동시 스크롤 맨위로 고정되도록
